### ISSUE TITLE
Run Configuration doesn't add multiple versions of a bundle

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-pde/eclipse.pde#433] opened 2023-01-18 13:08 UTC
Currently, m2e uses gson 2.10.1 and 2.9.1; both are included in the Run Configuration, either with "Include all available plugins" or with explicitly selecting the included plugins, selecting both versions.
The clicking "Validate" shows that the older version seems ignored and thus missing; running the configuration (starting an IDE) shows in the Installation Details of the application under test that the older gson is not included. As a result, it seems currently not possible to properly debug m2e as a whole.
I've seen other cases like this for other projects.
This is a blocker for several development workflows.

**Comment by laeubi** [comment] 2023-01-18 13:21
I think you need to use feature for this (I have created a feature based product for such purpose that you can turn into a run config).

**Comment by mickaelistria** [comment] 2023-01-18 15:27
> I think you need to use feature for this

That can be a workaround, but I don't want to use features for this on the long term. Having mulitple versions of a bundle in the launch config used to work.

**Comment by HannesWell** [comment] 2023-01-18 20:22
Actually it is possible to add multiple versions of a Plugin/Bundle or a Feature to a Run-Configuration and that is tested extensively in [PluginBasedLaunchTest](https://github.com/eclipse-pde/eclipse.pde/blob/master/ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/PluginBasedLaunchTest.java) and friends.

> The clicking "Validate" shows that the older version seems ignored and thus missing; running the configuration (starting an IDE) shows in the Installation Details of the application under test that the older gson is not included.

What you are experiencing is probably a result of the resolution failure in the TP, similar like https://github.com/eclipse-pde/eclipse.pde/issues/429:

![grafik](https://user-images.githubusercontent.com/44067969/213286320-06a12e03-36db-4954-81b7-5b4c1e732577.png)



If you add the required older gson bundle version to the provided Run-config for m2e (as extra Bundle, since that config is based on features) you can simply continue after the validation error message and everything works in the launched eclipse and you can even verify in the About dialog that both gson versions are present.

Just like https://github.com/eclipse-pde/eclipse.pde/issues/429 I can have a look for this (hopefully at the weekend).

**Comment by mickaelistria** [comment] 2023-01-19 01:34
> If you add the required older gson bundle version to the provided Run-config for m2e (as extra Bundle, since that config is based on features) you can simply continue after the validation error message and everything works in the launched eclipse and you can even verify in the About dialog that both gson versions are present.

That's not what I see with I20230113-1800
Target Platform:
![Screenshot from 2023-01-19 02-29-11](https://user-images.githubusercontent.com/469058/213334265-537791b2-75a8-4453-898b-28fca79755d8.png)
Launch config:
![Screenshot from 2023-01-19 02-30-27](https://user-images.githubusercontent.com/469058/213334402-aa4cb46c-1101-44d1-8e45-a0ea9978534b.png)
Validation:
![Screenshot from 2023-01-19 02-32-43](https://user-images.githubusercontent.com/469058/213334700-9fe3e170-8017-4420-90c5-9004bae29e3d.png)
Launched application:
![Screenshot from 2023-01-19 02-33-47](https://user-images.githubusercontent.com/469058/213334795-e78dee89-5945-40a1-b4a8-330cd5b2191e.png)

**Comment by HannesWell** [comment] 2023-01-19 23:24
Can you provide a screenshot of your Target-Platform State view?

The difference in the Launch config (based on explicitly selected bundles) and the installation details is indeed strange. Because in general that should work and I tested it successfully with m2e's provided launch config (which is based on features and I added it as extra Plugin. Maybe that's a difference). Nevertheless AFAICT nothing was changed in that area in the near past.

**Comment by mickaelistria** [comment] 2023-01-20 08:52
Here is the requested screenshot:
![Screenshot from 2023-01-20 09-50-50](https://user-images.githubusercontent.com/469058/213654323-505ffc39-bd4b-4c02-916d-03172efa8b6e.png)
Note the red cross of LSP4J bundles (I don't know what they mean)

> which is based on features and I added it as extra Plugin. Maybe that's a difference

Most likely yes.

> Nevertheless AFAICT nothing was changed in that area in the near past.

I can't tell if the regression is from near past or a more distant path; maybe it's 1 year old and I never had the use-case revealing it so far.

**Comment by mickaelistria** [comment] 2023-01-25 14:17
Here is a reproducer attached: 
[missing-bundle.zip](https://github.com/eclipse-pde/eclipse.pde/files/10500136/missing-bundle.zip)
From a fresh workspace, import all projects in the zip, import the .launch file as well and try to run it.

**Comment by mickaelistria** [comment] 2023-01-25 15:35
I could verify that the generated `workspace/.metadata/.plugins/org.eclipse.pde.core/d.id1/org.eclipse.equinox.simpleconfigurator/config.ini` misses a reference to `a1` in the `osgi.bundes` property; similarly with other launch configs about gson, `workspace/.metadata/.plugins/org.eclipse.pde.core/IDE-with-JDTLS/org.eclipse.equinox.simpleconfigurator/bundles.info` does miss the older gson.
I'm looking at PluginBasedLaunchTest and see some tests do cover the case of multiple bundles and seem to be successful; it seems like they do not assert the right thing or do not assert strictly enough. This seems to tell that BundleLauncherHelper behaves correctly and that the issue happens later. I don't think writing further tests is necessary to showcase the issue, just improving the checks to get to later phase (generating the application configuration files) in existing ones can be enough.

**Comment by mickaelistria** [comment] 2023-01-25 16:36
I suspect it's a regression from 5087f5db305fbdf1d1fcb7d0dcde03ed3261fe58 / https://bugs.eclipse.org/bugs/show_bug.cgi?id=577118 which improved the validation but then may have caused issues later in the process.

**Comment by HannesWell** [comment] 2023-01-26 09:30
Thanks Mickael for the reproducer and Investigation. I can have a look at this in the next days.

**Comment by HannesWell** [comment] 2023-01-27 00:57
I can reproduce the issue with your example.

> I suspect it's a regression from [5087f5d](https://github.com/eclipse-pde/eclipse.pde/commit/5087f5db305fbdf1d1fcb7d0dcde03ed3261fe58) / https://bugs.eclipse.org/bugs/show_bug.cgi?id=577118 which improved the validation but then may have caused issues later in the process.

In that change I improved the handling of multiple version with the same BSN, but it looks like I only covered the case where the `org.eclipse.equinox.simpleconfigurator` is present and therefore a bundles.info is written and simply oversaw the case when the bundle-set of the application is listed as osgi.bundles in the `config.ini`. Therefore I don't think it is a regression, but more a missing part that you addressed in #441.
Because when I'm on the current master and add `org.eclipse.equinox.simpleconfigurator` to the launch config you provided, it launches without errors and prints `OK!` (which I think the application in `d` is supposed to do?).

**Closed** 2023-01-29 19:06 UTC
Labels: bug, regression
