### ISSUE TITLE
Blank workbench on macOS aarch64

### ISSUE THREAD

**Issue by leviathan747** [eclipse-pde/eclipse.pde#1211] opened 2024-03-21 15:08 UTC
When I try to launch the `org.eclipse.platform.ide` project with default configuration, I get a blank workbench screen. I can still click items that would be on the screen, but nothing is visible. I do not see any errors in the log (see below).

This is with Eclipse 2024-03 on macOS Sonoma.

<img width="1098" alt="image" src="https://github.com/eclipse-pde/eclipse.pde/assets/2875522/7ce8fd54-7561-467c-8ffa-7597d4ba57bc">

<img width="1726" alt="image" src="https://github.com/eclipse-pde/eclipse.pde/assets/2875522/85c728f3-69fe-47b2-8e5e-5e4c47e04856">

Log:
```
!SESSION 2024-03-21 11:03:34.945 -----------------------------------------------
eclipse.buildId=4.31.0.20240307-1200
java.version=17.0.10
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.rcp.product -keyring /Users/levi/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.rcp.product -keyring /Users/levi/.eclipse_keyring

!ENTRY ch.qos.logback.classic 1 0 2024-03-21 11:03:35.882
!MESSAGE Activated before the state location was initialized. Retry after the state location is initialized.

!ENTRY ch.qos.logback.classic 1 0 2024-03-21 11:03:45.270
!MESSAGE Logback config file: /Users/levi/eclipse-workspace/.metadata/.plugins/org.eclipse.m2e.logback/logback.2.6.0.20240217-1525.xml
```

**Comment by merks** [comment] 2024-03-21 16:33
Duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012

**Closed** 2024-03-21 17:58 UTC
