### ISSUE TITLE
PDE new plug-in wizard fails with NPE in Build id: I20240130-1800

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#1097] opened 2024-01-31 07:44 UTC
In a new workspace with latest I-Build I get an NPE if I try to create a new plug-in project

![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/ed355195-79b1-4845-9117-48b591051a34)

java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Button.removeSelectionListener(org.eclipse.swt.events.SelectionListener)" because "this.cancelButton" is null
	at org.eclipse.jface.wizard.WizardDialog.aboutToStart(WizardDialog.java:401)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1026)
	at org.eclipse.pde.internal.ui.wizards.plugin.NewPluginProjectWizard.getAvailableCodegenWizards(NewPluginProjectWizard.java:209)
	at org.eclipse.pde.internal.ui.wizards.plugin.NewPluginProjectWizard.addPages(NewPluginProjectWizard.java:118)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:634)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1092)
	at org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(WizardShortcutAction.java:98)
	at org.eclipse.ui.internal.views.helpers.EmptyWorkspaceHelper$1.linkActivated(EmptyWorkspaceHelper.java:283)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:215)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:309)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.lambda$3(AbstractHyperlink.java:117)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

**Comment by vogella** [comment] 2024-01-31 07:44
If I go via the menu path, this works.

**Comment by vogella** [comment] 2024-01-31 07:47
cc @laeubi (if think you recently worked on the wizards)

**Comment by laeubi** [comment] 2024-01-31 07:51
Seems more a bug in jface here:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Button.removeSelectionListener(org.eclipse.swt.events.SelectionListener)" because "this.cancelButton" is null
at org.eclipse.jface.wizard.WizardDialog.aboutToStart(WizardDialog.java:401)
at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1026)
```

it assumes the button is already there what seems not the case.

**Comment by laeubi** [comment] 2024-02-12 05:23
@basilevs thanks for the reminder, I have created a PR that will hopefully be merged soon, can you retry after that with current IBuilds?

**Closed** 2024-02-12 07:22 UTC

**Comment by basilevs** [comment] 2024-02-13 19:17
I wanted to test this, added an update site to my PDE and update failed with:
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Eclipse Platform 4.31.0.v20240212-1900 (org.eclipse.platform.feature.group 4.31.0.v20240212-1900)
  Software currently installed: Eclipse IDE for Eclipse Committers 4.31.0.20240201-1200 (epp.package.committers 4.31.0.20240201-1200)
  Only one of the following can be installed at once: 
    Compare Support 3.10.0.v20240208-0728 (org.eclipse.compare 3.10.0.v20240208-0728)
    Compare Support 3.10.0.v20240125-0912 (org.eclipse.compare 3.10.0.v20240125-0912)
  Cannot satisfy dependency:
    From: Eclipse IDE for Eclipse Committers 4.31.0.20240201-1200 (epp.package.committers 4.31.0.20240201-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.31.0.v20240127-1800,4.31.0.v20240127-1800]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.31.0.v20240127-1800 (org.eclipse.platform.feature.group 4.31.0.v20240127-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.compare [3.10.0.v20240125-0912,3.10.0.v20240125-0912]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.31.0.v20240212-1900 (org.eclipse.platform.feature.group 4.31.0.v20240212-1900)
    To: org.eclipse.equinox.p2.iu; org.eclipse.compare [3.10.0.v20240208-0728,3.10.0.v20240208-0728]
```
This is caused by the nature of the main product feature (Eclipse for Committers), which has to be updated atomically. I wonder how do people test development builds without complete reinstall.

I've then installed Eclipse Platform, installed PDE from https://download.eclipse.org/eclipse/updates/4.31-I-builds/I20240212-1800/ and successfully opened new plugin wizard.

**Comment by laeubi** [comment] 2024-02-14 07:39
@basilevs yes thats really annoying, sadly I failed with all attempts in the past to losen that, so in contrast to [what is stated here](https://download.eclipse.org/eclipse/downloads/drops4/I20240213-1800/) it is *not* possible to update any EPP package (FYI @jonahgraham ) to this stream but only if you are using a SDK downloaded from that page previously and build your own. Another option is probably using oomph (FYI @merks ) but I never tried that path.

But thanks for testing this and sorry for any inconvenience!
