### ISSUE TITLE
New 4.24 JDT feature to run JUnit5 failures first requires change to RemotePluginTestRunner

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-pde/eclipse.pde#117] opened 2022-05-19 15:58 UTC
The new JDT feature to run failures first uses a MethodOrderer class that is specifed in org.eclipse.jdt.junit5.runtime.  The building of the test plan eventually calls the junit engine which cannot find the class because it is not in the engines bundles nor is required by the user's test plug-in.  To fix this, the bundle needs to be added for JUnit5 plug-in testing.

This fix is requested for 4.24 RC1.

This was originally opened as: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/57

**Comment by iloveeclipse** [comment] 2022-05-23 06:34
This seem to cause two new test fails in [org.eclipse.pde.junit.runtime.tests](https://download.eclipse.org/eclipse/downloads/drops4/I20220522-1800/testresults/html/org.eclipse.pde.junit.runtime.tests_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html#org.eclipse.pde.junit.runtime.tests)

```
test application could not start

!ENTRY org.eclipse.test 4 0 2022-05-23 00:21:36.161
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.test [238]
Unresolved requirement: Require-Bundle: org.junit.vintage.engine

at org.eclipse.osgi.container.Module.start(Module.java:463)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.test 2 0 2022-05-23 00:21:37.348
!MESSAGE Could not resolve module: org.eclipse.test [238]
Unresolved requirement: Require-Bundle: org.junit.vintage.engine


!ENTRY org.eclipse.osgi 4 0 2022-05-23 00:21:37.348
!MESSAGE Application error
!STACK 1
java.lang.IllegalArgumentException: Bundle "null" not found.
at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.createJUnit5PluginClassLoader(RemotePluginTestRunner.java:87)
at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:72)
at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.start(CoreTestApplication.java:28)
```

**Comment by vik-chand** [comment] 2022-05-23 06:49
caused by
if (junit5RuntimeBundle == null) {
			throw new IllegalArgumentException("Bundle \"" + junit5RuntimeBundle + "\" not found."); //$NON-NLS-1$ //$NON-NLS-2$
		}

**Comment by vik-chand** [comment] 2022-05-23 06:50
Not sure why the tests triggered by pr didn't catch this issue.

**Comment by vik-chand** [comment] 2022-05-23 10:52
Fixed with https://github.com/eclipse-pde/eclipse.pde/pull/119

**Closed** 2022-05-23 10:52 UTC
