### ISSUE TITLE
Validation error when launching child eclipse

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-pde/eclipse.pde#194] opened 2022-07-01 10:18 UTC
We are getting this error
![image](https://user-images.githubusercontent.com/77106773/176875646-0fdfb7cd-251b-42f0-a8b9-a64d67f17281.png)

All these are for JDK packages. 

Build information:
Eclipse SDK
Version: 2022-06 (4.25)
Build id: I20220630-1800
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.3+7
Java version: 17.0.3

Notifications: @SarikaSinha @akurtakov

**Comment by sravanlakkimsetti** [comment] 2022-07-01 11:46
These packages got added in Import-package directive in latest Jetty (version 10.0.11)

java.io,
java.lang,
java.lang.invoke,
java.net,
java.nio,
java.nio.channels,
java.nio.charset,
java.text,
java.util,
java.util.concurrent,
java.util.concurrent.atomic,
java.util.function,
java.util.regex,
java.util.stream,
java.util.zip,

**Comment by vik-chand** [comment] 2022-07-05 05:58
Happens 1st on 28th June build

gitlog of 28th 

2022-06-28	[Build input for build I20220628-1800](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/91f2e35dc3387bb556a1d7ff26694e726ad9226e)	Eclipse Releng Bot
2022-06-28	[Build input for build I20220628-1040](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/1099db163dcc053d65ac432e952a5cfde3469030)	Eclipse Releng Bot
2022-06-28	[Update to Jetty 10.0.11](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/bdf0a0b44e8f31fa2b38b6695367103fced40514)	Александър Куртаков

**Comment by vik-chand** [comment] 2022-07-05 06:02
<img width="916" alt="image" src="https://user-images.githubusercontent.com/99390647/177259941-c86c6b8d-cc0e-4fc9-9196-9ccd7132d123.png">

**Comment by vik-chand** [comment] 2022-07-05 06:16
I removed the import packages of  comment#2 (by Sravan) in org.eclipse.jetty.http and that particular no longer is in the list of validation error.

Another issue is why org.eclipse.osgi.internal.resolver.UserState@492d0748 cant resolve import of java.io etc

**Comment by vik-chand** [comment] 2022-07-05 06:21
If I add "Import-Package: java.io" manually in manifest of pde.core, plugin validation give pde.core also as the offending plugin.

**Comment by sravanlakkimsetti** [comment] 2022-07-05 06:27
Shouldn't we resolve JDK libraries?

**Comment by merks** [comment] 2022-07-05 06:28
Yes, one really kind of needs the a.jre.javase IU (or equivalent there of) corresponding to the selected JRE of the launcher to verify that the required packages are really in the actual JRE.   But that's easier said than done.

**Comment by vik-chand** [comment] 2022-07-05 07:10
While resolving the bundle org.eclipse.jetty.http in ResolverImpl for org.eclipse.jetty.http

		if (!failed) {
			// Iterate thru imports of 'bundle' trying to find matching exports.
			ResolverImport[] imports = bundle.getImportPackages();
			for (ResolverImport resolverImport : imports) {
				// Only resolve non-dynamic imports here
				if (!resolverImport.isDynamic() && !resolveImport(resolverImport, cycle)) {

For ResolverImport (java.io)

	// Resolve the supplied import. Returns true if the import can be resolved, false otherwise
	private boolean resolveImport(ResolverImport imp, List<ResolverBundle> cycle) {
		if (DEBUG_IMPORTS)
			ResolverImpl.log("Trying to resolve: " + imp.getBundle() + ", " + imp.getName()); //$NON-NLS-1$ //$NON-NLS-2$
		if (imp.getSelectedSupplier() != null) {
			

imp.getSelectedSupplier() comes as null

**Comment by vik-chand** [comment] 2022-07-05 07:12
The above is causing the resolve of org.eclipse.jetty.http to fail in OSGI.

**Comment by vik-chand** [comment] 2022-07-05 07:13
@tjwatson Can you provide your views on this?

**Comment by laeubi** [comment] 2022-07-05 07:47
> Yes, one really kind of needs the a.jre.javase IU (or equivalent there of) corresponding to the selected JRE of the launcher to verify that the required packages are really in the actual JRE. But that's easier said than done.

This is an ancient (one can't really call it old anymore) bug in PDE, and to clarify this is not an Validation **error** but a **warning**, and it does not really require a a.jre.javase IU as this all can be derived from the selected JDK itself (and P2 already do that for the workspace JRE).

> The above is causing the resolve of org.eclipse.jetty.http to fail in OSGI.

Can you show the exact error? This should only fail if using OSGi <= 6, at all as it is valid to import java packages since OSGi R7:
https://blog.osgi.org/2018/02/osgi-r7-highlights-java-9-support.html

**Comment by laeubi** [comment] 2022-07-05 07:53
> But that's easier said than done.

That's really not that hard, Tycho uses the following to get all system-packages of a JVM:
https://github.com/eclipse/tycho/blob/master/tycho-core/src/main/java/org/eclipse/tycho/core/ee/ListSystemPackages.java

**Comment by merks** [comment] 2022-07-05 07:58
Yes, though that requires launching the JRE.   And in the end, I believe that JDT has already computed all the packages of each JVM so it's just a matter of creating an IU like the a.jre.javase IU with those package capabilities...

**Comment by laeubi** [comment] 2022-07-05 08:02
> Yes, though that requires launching the JRE. And in the end, I believe that JDT has already computed all the packages of each JVM 

Probably yes :-)

> so it's just a matter of creating an IU like the a.jre.javase IU with those package capabilities...

I thin this is just relevant for P2, the problem is that PDE uses "old" OSGi API and that these packages are superposed to be exported by the system-bundle dynamically, so at least PDE must handle this and hopefully could finally throw away the java**x** is from JRE assumption so we can get better errors / warnings at the first place.

**Comment by merks** [comment] 2022-07-05 08:09
I'm just pointing out that "the system bundle information" must be the one that would be specified for the actual JRE of the launcher, not the one of the running IDE itself.

**Comment by laeubi** [comment] 2022-07-05 08:12
> I'm just pointing out that "the system bundle information" must be the one that would be specified for the actual JRE of the launcher, not the one of the running IDE itself.

Yep, int this case it is actually the Target-JRE.

**Comment by vik-chand** [comment] 2022-07-05 11:50
> A note from other perspective: the same error will be shown also if we debug from "old" Eclipse against new target platform containing Jetty. I know we usually say "just update to latest", but if that is impossible, people will be angry too.
> 
> So **why** Jetty is requiring now system packages at all? What''s the point doing that? Shouldn't we fix Jetty manifest instead? This would allow "older" Eclipse versions to be used with new Jetty too (assuming we will find solution for 4.25).

See bug -> https://github.com/eclipse/jetty.project/issues/8265

**Comment by vik-chand** [comment] 2022-07-05 11:54
Notification @bjhargrave

**Comment by HannesWell** [comment] 2022-07-05 11:57
For those that are asking if these packages are generated intentionally (by BND), the answer is yes:
https://github.com/bndtools/bnd/issues/4348

**Comment by laeubi** [comment] 2022-07-05 12:00
> So **why** Jetty is requiring now system packages at all? What''s the point doing that?
> Shouldn't we fix Jetty manifest instead?

There is nothing to fix see https://blog.osgi.org/2018/02/osgi-r7-highlights-java-9-support.html

**Comment by merks** [comment] 2022-07-05 12:00
Why should Jetty do this?  These days it's quite possible to use jlink to create reduced JREs which may not provide all the packages.  By declaring it needs a certain package it's ensuring that there won't just be class not found exceptions but rather that it's clear a certain package is needed and not present...

**Comment by bjhargrave** [comment] 2022-07-05 12:10
In OSGi Core Release 7, it became supported to import `java.*` packages when the code targets Java 9+. See <https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-execution.environment>.

So Bnd supports this. An OSGi R7 framework when running on Java 9+ will export all the available `java.*` packages from the system bundle so any bundle importing `java.*` packages will resolve _IF_ the Java 9+ runtime has been configure with all the modules needed to support the bundle's `java.*` imports.

It appears here that parts of Eclipse (PDE) do not properly handle this.

Bnd has a `-noimportjava: true` option which can be used to tell Bnd not to declare imports on `java.*` packages. See <https://bnd.bndtools.org/instructions/noimportjava.html>. But Jetty is allowed to import `java.*` packages. Tooling needs to be updated to handle this.

**Comment by HannesWell** [comment] 2022-07-05 12:14
I can offer to try to fix this false positive validation error in the next days (for the current PDE).

> That's really not that hard, Tycho uses the following to get all system-packages of a JVM: https://github.com/eclipse/tycho/blob/master/tycho-core/src/main/java/org/eclipse/tycho/core/ee/ListSystemPackages.java
> 
... with this in mind it should be straight forward.

Anybody that is interested in having this fix in older versions is then free to backport it. :)

Just for curiosity, would this automatically be fixed if PDE migrates off Resolver-State in the `o.e.osgi.compatibility.state` fragment?

**Comment by laeubi** [comment] 2022-07-05 12:23
> Just for curiosity, would this automatically be fixed if PDE migrates off Resolver-State in the `o.e.osgi.compatibility.state` fragment?

Have not checked this, but I think it is more that the current target platform state need to consider the packages of the selected target-jre instead. and not really related to the `o.e.osgi.compatibility.state`

**Comment by vik-chand** [comment] 2022-07-05 12:49
>>I can offer to try to fix this false positive validation error

We should try to fix this in M1 since this is rather annoying validation error ( which kind-of suggests that the launch is not good) . If this is not fixed, we should also consider rollback of jetty update for M1.

**Comment by laeubi** [comment] 2022-07-05 14:49
> All that complication would need to be placed in the PDE implementation of a ResolveContext if they want to limit what packages from the JVM can import based on their required execution environment.

I don't think this is needed, actually a Target hat a JVM and that has to be used instead of an individual per bundle.

**Comment by HannesWell** [comment] 2022-07-05 23:04
> > Just for curiosity, would this automatically be fixed if PDE migrates off Resolver-State in the `o.e.osgi.compatibility.state` fragment?
> 
> Have not checked this, but I think it is more that the current target platform state need to consider the packages of the selected target-jre instead. and not really related to the `o.e.osgi.compatibility.state`

I created a minimal reproducer for this case and the first thing I noticed is that a Plug-in that has for example a `Import-Package: java.io` resolves without errors.
You can also check in the target-platform state view that the `o.e.jetty.http` bundle has no resolution errors (unlike for example the currently flawed org.apache.xml.resolver bundle, see https://github.com/eclipse-pde/eclipse.pde/issues/130).
Furthermore I verified that the BundleDescription's Wiring of such Plug-in has a package-wire dedicated to its Export-Package `java.io` whose capability is provided by the System-Bundle.
So in general the Target-Platform State considers those java.* packages provided by the system bundle and seems to handle them well. So I suspect this is a issue specific to the `EclipsePluginValidationOperation` (or its super class) respectivly in the way the state that is used for validation is set up.
I will investigate that further.

**Comment by laeubi** [comment] 2022-07-06 03:10
> So I suspect this is a issue specific to the `EclipsePluginValidationOperation` (or its super class) respectivly in the way the state that is used for validation is set up.

Yes as mentioned the validation often shows some false-positives while it misses others, I think this is because it does not use the TargetState as is (what could e.g. contain lots of stuff not in the product) but computes a new closure of just the product content.

**Comment by vik-chand** [comment] 2022-07-06 04:35
Related issue -> Reported warnings may not be accurate because **org.eclipse.equinox.http.jetty has 1 resolution problems.**
See https://download.eclipse.org/eclipse/downloads/drops4/I20220705-1800/apitools/analysis/html/index.html
I have opened https://github.com/eclipse-equinox/equinox.bundles/issues/66

**Comment by laeubi** [comment] 2022-07-06 04:38
@vik-chand what do you expect equinox to do here? This sounds like an API-Tools problem...?

**Comment by HannesWell** [comment] 2022-07-06 07:20
> > So I suspect this is a issue specific to the `EclipsePluginValidationOperation` (or its super class) respectivly in the way the state that is used for validation is set up.
> 
> Yes as mentioned the validation often shows some false-positives while it misses others, I think this is because it does not use the TargetState as is (what could e.g. contain lots of stuff not in the product) but computes a new closure of just the product content.

My experience until know was that the validation only shows false-positive errors if the Target Platform State has resolution errors, like in https://github.com/eclipse-pde/eclipse.pde/issues/130. With the new automatic addition of requirements I never saw this dialog again, given that the Target-Platform-State was resolution error free. Therefore this was remarkable for me.
But maybe I just use simple plug-ins or were lucky.

**Closed** 2022-07-06 09:24 UTC

**Comment by vik-chand** [comment] 2022-07-06 09:34
I have committed a workaround for M1. @HannesWell  please feel free to revert it if you have a fix or a better workaround.

**Comment by vik-chand** [comment] 2022-07-06 09:37
> Would be nice to have a workaround / solution also for #158 or more general #130

yes but it is not as general case as launching child eclipse.  If someone provides a fix/workaround , that will be good

**Comment by akurtakov** [comment] 2022-07-11 04:26
@HannesWell are you working on this one ?

**Comment by HannesWell** [comment] 2022-07-11 06:03
> @HannesWell are you working on this one ?

Yes, I started to work on this but didn't find a solution how to fix that yet. I noticed that in the state for the TP  the Java packages are resolved, but not in the state for the validation. 
At the moment I suspect that it has something to with that all available EEs are thrown in the validation state.

But I'm on vacation until Friday and plan to continue the work then.

**Comment by Phillipus** [comment] 2022-07-18 09:06
I've just encountered this issue testing our RCP app against a target of the latest 4.25 I builds using Eclipse 4.24 as a host.

If I use the latest 4.25 I build as a host, there are no errors.

I'm not clear from the previous discussion if there is planned a change that will allow 4.24 to be used as host when targetting 4.25, or whether 4.25 will be required as host?

**Comment by laeubi** [comment] 2022-07-18 09:21
> If I use the latest 4.25 I build as a host, there are no errors.

These are not errors, just warnings.

> I'm not clear from the previous discussion if there is planned a change that will allow 4.24 to be used as host when targetting 4.25, or whether 4.25 will be required as host?

Simply click `Continue` button ...

**Comment by Phillipus** [comment] 2022-07-18 09:46
> These are not errors, just warnings.

Yes, indeed.

> Simply click `Continue` button ...

Right. Or untick the launch configuration option `Validate Plug-ins automatically prior to launching`

**Comment by HannesWell** [comment] 2022-07-18 23:40
Created https://github.com/eclipse-pde/eclipse.pde/pull/221 that should fix this issue.
Verified it with the mentioned o.e.jetty.http and a workspace Plug-in with `Import-Package: java.io`.
