### ISSUE TITLE
Plug-in JUnit Launch does not detec Junit5 tests

### ISSUE THREAD

**Issue by Pontesegger** [eclipse-pde/eclipse.pde#390] opened 2022-11-08 15:07 UTC
Beginning from 2022-09 I am not able to execute JUnit Plug-in Tests. Works fine with 2022-06 IDE.

My Setup:
* Tests provided within fragment project
* Target definition based on 2022-06
* Test fragment dependend on:
    org.junit.jupiter.api
    org.junit.jupiter.params
* Execution environment: Java17

When installing an IDE 2022-06 I have a context menu Run As -> JUnit Plug-in Test.
Further tests execute fine and results are displayed in the JUnit view.

Now I switched to an IDE 2022-09, keeping the rest of my setup above.

Finding 1) the context menu entry Run As -> JUnit Plug-in Test is gone. To make it reappear I have to add following dependencies to my fragment:
   org.junit.platform.commons;bundle-version="1.8.1",
   org.junit.platform.engine;bundle-version="1.8.1",
   org.junit.jupiter.engine;bundle-version="5.8.1"

Finding 2) With the context menu back I can launch Unit tests, but after execution the JUnit view shows 0 tests. Trying to run with coverage reveals that the test code is actually not executed.

Followed it down to RemoteTestRunner.java#516
The count returned is always 0, so test discovery somehow does not work.

**Comment by mickaelistria** [comment] 2022-11-08 15:34
This indeed seems like a bug. Platform adopted upstream junit-* bundles in last release instead of Orbit's variant org.junit.*. PDE was supposed to work with both equally, but it looks like this doesn't work as well as expected.
I would recommend that -if you use a recent IDE and a recent Tycho- you simply stop using org.junit* bundles and instead use junit-* ones. PDE and Tycho would be happy with it.

**Comment by Pontesegger** [comment] 2022-11-08 17:11
Does eclipse then ship junit.* plugins? At least 2022-06 does not seem to have such plug-ins. So which kind of dependencies do you declare for IDE/tycho? Any examples?

**Comment by akurtakov** [comment] 2023-09-08 07:14
Is this still an issue?

**Comment by HannesWell** [comment] 2024-09-26 20:49
Duplicate of #650

**Closed by HannesWell** 2024-09-26 20:49 UTC
