### ISSUE TITLE
java.lang.Exception: The resource tree is locked for modifications.

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#64] opened 2022-05-02 09:52 UTC
I don't remember what exactly i did (something like open/closing project), just found it in my logfile. Maybe somebody can see in exception whats wrong?
java.lang.Exception: The resource tree is locked for modifications.
```
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:122)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2324)
	at org.eclipse.core.internal.resources.File.create(File.java:108)
	at org.eclipse.core.internal.resources.File.create(File.java:181)
	at org.eclipse.pde.internal.core.SearchablePluginsManager.saveStates(SearchablePluginsManager.java:427)
	at org.eclipse.pde.internal.core.SearchablePluginsManager.resetContainer(SearchablePluginsManager.java:360)
	at org.eclipse.pde.internal.core.SearchablePluginsManager.modelsChanged(SearchablePluginsManager.java:376)
	at org.eclipse.pde.internal.core.PluginModelManager.fireDelta(PluginModelManager.java:399)
	at org.eclipse.pde.internal.core.PluginModelManager.modelsChanged(PluginModelManager.java:297)
	at org.eclipse.pde.internal.core.AbstractModelManager.fireModelProviderEvent(AbstractModelManager.java:37)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.createAndFireEvent(WorkspaceModelManager.java:283)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.createAndFireEvent(WorkspacePluginModelManager.java:552)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(WorkspaceModelManager.java:262)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(WorkspaceModelManager.java:220)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.processModelChanges(WorkspacePluginModelManager.java:541)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.resourceChanged(WorkspaceModelManager.java:144)
	at org.eclipse.jdt.internal.core.DeltaProcessingState$1.run(DeltaProcessingState.java:496)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:489)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:160)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:385)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1509)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:49)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by iloveeclipse** [comment] 2022-05-02 11:39
The problem is, that while resource tree is locked, someone (PDE) tries to modify resources **without** requesting a lock (so neither in a job with appropriate rule nor by manually locking file that is written).
This is disallowed, so exception.
The code in https://github.com/eclipse-pde/eclipse.pde/blob/3f9f33643122a8109460e88362593d67fde42ed5/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/SearchablePluginsManager.java#L425 should be fixed to avoid that.

**Comment by jukzi** [comment] 2022-06-21 13:54
to reproduce: add PDEs "External Plug-in Libraries" project and close/open a project. During the Notifcation the workspace is locked. The update of the PROXY should be scheduled for another job.

**Comment by gireeshpunathil** [comment] 2023-02-06 06:47
I would like to take this up.

@jukzi - I tried reproducing this error, but could not. I might have missed some steps, so just wondering if you could throw some light. This is what I did:
 
- created a java project
 - eclipse -> preferences -> plug-in development -> include all plug-ins from target in java workspace scope
 - apply and close
 - while the `External plug-in libraries` is being created, closed and re-opened the java project
 
did not see any error, and both operations succeeded. Am I missing anything?

**Comment by jukzi** [comment] 2023-02-06 09:19
@gireeshpunathil thanks for taking care.
You need to create a plugin project instead of a java project.
It might be some timing issue: the Shortcut "loadedStates.equals(fPluginIdSet)" may return true and noting happens.
You can just comment out the eager "return" in SearchablePluginsManager.saveStates() line 412, then it will crash every time. The save seems to just never work if it ever tries to really save.

**Closed** 2023-04-04 11:34 UTC
