### ISSUE TITLE
Avoid adding all known artifact repositories during target resolution

### ISSUE THREAD

**Issue by merks** [eclipse-pde/eclipse.pde#881] opened 2023-11-05 09:53 UTC
The following seems highly questionable to me:

https://github.com/eclipse-pde/eclipse.pde/blob/3f9410787872dabfff01e5108238caf66f395da8/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java#L1417-L1419

When resolving a target platform, one generally expects that primarily only the repositories mentioned in the target platform resource will be used.   But what the above line of code does is add all enabled repositories listed in Window -> Preferences -> Install/Update -> Available Software Sites.  That just seems very wrong.  

I think the intent here is likely that IRepositoryManager.REPOSITORIES_LOCAL should be used.  I.e., it's a performance optimization to provide local artifact repositories that might contain the artifacts and from which one could transfer those artifacts much more quickly than from a remote site.  Adding more remote sites can and often does hurt performance...

**Comment by laeubi** [comment] 2023-11-05 10:04
> I think the intent here is likely that IRepositoryManager.REPOSITORIES_LOCAL should be used. I.e., it's a performance optimization to provide local artifact repositories that might contain the artifacts and from which one could transfer those artifacts much more quickly than from a remote site

Sounds reasonable. I think the name useAdditional**Local**Artifacts() also implies this, I would vote for:

1. remove `useAdditionalLocalArtifacts()` as it always returns true and obviously never was implementede/enhanced
2. use unconditional `result.addAll(Arrays.asList(manager.getKnownRepositories(IRepositoryManager.REPOSITORIES_LOCAL)));`

Especially as Tycho does not use something similar and we never got any complaint about something working in PDE but not for Tycho in this regards...

@HannesWell @vik-chand any concerns?

**Comment by HannesWell** [comment] 2023-11-05 11:07
> When resolving a target platform, one generally expects that primarily only the repositories mentioned in the target platform resource will be used. But what the above line of code does is add all enabled repositories listed in Window -> Preferences -> Install/Update -> Available Software Sites. That just seems very wrong.

Absolutely. At least this is only used to get the artifacts and not also the metadata, which would mean that always the latest repo available as update-site is used.

> * remove `useAdditionalLocalArtifacts()` as it always returns true and obviously never was implementede/enhanced
> 
> * use unconditional `result.addAll(Arrays.asList(manager.getKnownRepositories(IRepositoryManager.REPOSITORIES_LOCAL)));`

Full support from my side.

Btw. isn't that a duplicate of https://github.com/eclipse-pde/eclipse.pde/issues/793?

**Closed** 2023-11-05 15:33 UTC
