### ISSUE TITLE
API error on SWT "execution environments have been changed since"

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1283] opened 2024-06-03 08:45 UTC
I've set my baseline to 4.32RC2a build and see now this API error on SWT:

`The minor version should be incremented in version 3.126.0, since execution environments have been changed since version 3.126.0`

I'm not aware about any execution environment change in SWT, so why do we have that error now?
Is something broken again with API descriptions, like we had it in 4.31 (se https://github.com/eclipse-pde/eclipse.pde/issues/1187)?

**Comment by merks** [comment] 2024-06-03 12:40
The API baseline I find to be notoriously hard to update.   If you to to the preference, double click it and refresh it, does that help?  If not, restart, and do that again maybe helps?

**Comment by iloveeclipse** [comment] 2024-06-03 12:42
Does it mean, you can't reproduce? I see it on both my Linux/Windows workspaces, so I assume this should be reproducible.

**Comment by merks** [comment] 2024-06-03 12:58
I’m driving around so not tried yet. So it was just a thought.

**Comment by merks** [comment] 2024-06-03 13:59
Yes, I have that error too:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/2e96f43e-3c7f-4035-8f18-302eaa58efaf)

The thing doesn't have a BREE though and never did.   Last release cycle it was version bumped without a reason...

**Comment by merks** [comment] 2024-06-05 13:05
Debugging, here is the problem:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/c16cde23-4946-4758-ad28-b16265c2f947)

The API reference indicates there is no EE at all, but from the bundle description the current project computes that it has EE  Java-17 even though that value is not present in the MANIFEST.MF.

While building the description, the entry is in the map, but not in the file itself:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/55af3de5-3e17-4b71-af22-40f244bec7a2)

And finally, we see here that PDE is adding the EE property, computed from the JRE associated with the project, to the manifest properties as if it were present in the loaded resource:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/df8a3fde-614e-477c-a762-b1005d65eafb)

It's not entirely clear to me how to fix this problem.  For validation would need to should be able to distinguish between a computed/implicit default value versus an explicitly-present value...  I don't think it makes so much sense that the baseline ought to record some value not actually present and one that depends on the workspace's JRE.  Note in particular that if one associates the JavaSE-17 EE with a Java 21 JRE/JDK, the computed value changes:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/81494f51-552e-4989-bfd5-0e917471d8e6)

What to do...

**Comment by merks** [comment] 2024-06-05 14:12
It seems to me that every release I have this problem in SWT, and then it soon goes away.  In hindsight now, I expect it goes away because the first change to SWT increments versions and then presto, all is good again.  And then the next release cycle the problem comes back for a whoel while.  That's my theory.  

Also please read carefully what I wrote though.  The computed value depends on which JDK/JRE version is bound which which EE in the user's workspace.  So it is not correct, in my opinion, to store a EE **compute** value when none is specified.  Of course PDE must have some good reason to inject an EE as if one were specified for some appropriate reasons, but the validation step should know the difference between such a computed value (that may be different from workspace to workspace) versus an actual specified value that may be deliberated changed over time.

I looked at the whole call chain that is producing the description and see nothing that would allow such information to be recorded easily.   Perhaps via org.eclipse.osgi.service.resolver.BaseDescription.setUserObject(Object) if there isn't something else already using that "slot".

Of course another way to make this problem go away is to specify an EE.  😱

**Comment by iloveeclipse** [comment] 2024-06-05 14:56
Ed, I haven't looked into debugger / git history yet, but what I can't understand: why was it working **before**? 
The check was fine with whatever was computed or stored or not stored for 4.32.

**Comment by merks** [comment] 2024-06-05 15:35
Maybe the EE check was disabled but now that we have shared preferences maybe it's no longer disabled?

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/ab0fd1ec-9ad7-4129-ae2a-4cd2980b3c84)

**Comment by merks** [comment] 2024-06-05 15:36
I can't launch anymore now either.  😱 

> java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
> 	no swt-win32-4966 in java.library.path: C:\Program Files\Java\jdk-17.0.9+9\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/Program Files/Java/jdk-21.0.2+13/bin/server;C:/Program Files/Java/jdk-21.0.2+13/bin;C:/Program Files/Java/jdk-17.0.9+9/bin/server;C:/Program Files/Java/jdk-17.0.9+9/bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\merks\AppData\Local\Microsoft\WindowsApps;;D:\Users\merks\platform-sdk-4.31\eclipse;;D:\Users\merks\platform-sdk-4.31\eclipse;;.
> 	no swt-win32 in java.library.path: C:\Program Files\Java\jdk-17.0.9+9\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/Program Files/Java/jdk-21.0.2+13/bin/server;C:/Program Files/Java/jdk-21.0.2+13/bin;C:/Program Files/Java/jdk-17.0.9+9/bin/server;C:/Program Files/Java/jdk-17.0.9+9/bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\merks\AppData\Local\Microsoft\WindowsApps;;D:\Users\merks\platform-sdk-4.31\eclipse;;D:\Users\merks\platform-sdk-4.31\eclipse;;.
> 	no swt in java.library.path: C:\Program Files\Java\jdk-17.0.9+9\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/Program Files/Java/jdk-21.0.2+13/bin/server;C:/Program Files/Java/jdk-21.0.2+13/bin;C:/Program Files/Java/jdk-17.0.9+9/bin/server;C:/Program Files/Java/jdk-17.0.9+9/bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\merks\AppData\Local\Microsoft\WindowsApps;;D:\Users\merks\platform-sdk-4.31\eclipse;;D:\Users\merks\platform-sdk-4.31\eclipse;;.
> 	Can't load library: C:\Users\merks\.swt\lib\win32\x86_64\swt-win32-4966.dll
> 	Can't load library: C:\Users\merks\.swt\lib\win32\x86_64\swt-win32.dll
> 	Can't load library: C:\Users\merks\.swt\lib\win32\x86_64\swt.dll

**Comment by HannesWell** [comment] 2024-06-05 18:24
> I can't launch anymore now either. 😱
> 
Probably due to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2085#issuecomment-2150007561 ff

**Comment by iloveeclipse** [comment] 2024-06-05 18:26
> > I can't launch anymore now either. 😱
> 
> Probably due to [eclipse-platform/eclipse.platform.releng.aggregator#2085 (comment)](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2085#issuecomment-2150007561) ff

Not probably, for sure because of missing SWT native libraries.

**Comment by merks** [comment] 2024-06-05 18:31
I hope tomorrow is a better day.

**Comment by iloveeclipse** [comment] 2024-06-05 18:33
> I hope tomorrow is a better day.

My hope almost every day :)

**Comment by merks** [comment] 2024-06-06 10:43
It's a little tricky to test the older baseline because the logic is preempted by many earlier guards, but if I force it to reach the logic where it checks the BREEs, it's clear that the baseline for Eclipse 4.31 for this fragment also has no BREE in the baseline reference:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/5f8f8468-5160-47db-b54f-29c9bb334dd4)

So I don't think anything new is wrong nor that there was some regression.  The bottom line is that the API baseline reads purely the bundle in the API baseline and used purely the contents of the actual MANIFEST.MF which has no BREE to create the bundle description. The workspace bundles are created using the manifest as returned by org.eclipse.pde.internal.core.MinimalState.loadWorkspaceBundleManifest(File, IResource) which adds a synthetic computed BREE.  So the baseline will generally never have a BREE if there is no explicit BREE while the workspace bundle will generally always have a BREE even when there is no explicit BREE.

So my conclusion is that this can only be fixed in the API tools if there is somewhere, somehow, recorded information about whether the BREE the workspace bundle is implicit versus explicit.

**Comment by merks** [comment] 2024-06-06 14:22
I'll leave this open until I verify that the actual update tomorrow fixes this problem.

**Closed as completed** 2024-06-07 06:09 UTC
Labels: bug, api-tools
