### ISSUE TITLE
validateProduct test fails since I20230124-0530

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#437] opened 2023-01-25 17:10 UTC
See https://download.eclipse.org/eclipse/downloads/drops4/I20230124-0530/testresults/html/org.eclipse.pde.ui.templates.tests_ep427I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Seeing references to missing `jdom` I assume this is a regression from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/815

```
Generated product fails validation: [Missing Constraint: Import-Package: javax.servlet; version="0.0.0", Missing Constraint: Import-Package: javax.servlet.http; version="0.0.0", Missing Constraint: Import-Package: javax.servlet.jsp; version="0.0.0", Missing Constraint: Import-Package: org.apache.commons.beanutils; version="0.0.0", Missing Constraint: Import-Package: org.jdom; version="0.0.0", Missing Constraint: Import-Package: org.jdom.input; version="0.0.0"]

java.lang.AssertionError: Generated product fails validation:
[Missing Constraint: Import-Package: javax.servlet; version="0.0.0", Missing Constraint: Import-Package: javax.servlet.http; version="0.0.0", Missing Constraint: Import-Package: javax.servlet.jsp; version="0.0.0", Missing Constraint: Import-Package: org.apache.commons.beanutils; version="0.0.0", Missing Constraint: Import-Package: org.jdom; version="0.0.0", Missing Constraint: Import-Package: org.jdom.input; version="0.0.0"]
at org.junit.Assert.fail(Assert.java:89)
at org.eclipse.pde.ui.templates.tests.TestPDETemplates.validateProduct(TestPDETemplates.java:193)
```

@mickaelistria : please check.

**Comment by akurtakov** [comment] 2023-01-25 17:13
I'm pretty sure that the root cause is the same as the one preventing https://github.com/eclipse-pde/eclipse.pde/pull/434 to be merged.

**Comment by iloveeclipse** [comment] 2023-01-25 17:17
@akurtakov : I have no idea about things mentioned in #434.
The question for me: is this something that **must** be fixed because it is a production issue or is this just unfortunate test setup / data that can be fixed?

**Comment by akurtakov** [comment] 2023-01-25 17:18
It's a bug in PDE resolving IMO that wasn't covered by a test and this change exposes it.

**Comment by mickaelistria** [comment] 2023-01-25 17:22
The root cause may then be https://github.com/eclipse-pde/eclipse.pde/issues/429

**Comment by merks** [comment] 2023-01-25 17:22
@mickaelistria 

I was writing the text below this morning...

FYI, I wonder about actually properly using commons-jxpath though.   Testing indicates, as you noticed I think that the dependencies don't resolve:

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.oomph.maven.site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
[ERROR]   Missing requirement: org.apache.commons.jxpath 1.3.0 requires 'java.package; org.jdom 0.0.0' but it could not be found
```
The latest orbit has no bundle that provides such a package:

![image](https://user-images.githubusercontent.com/208716/214504520-4e5c06f0-4fb2-415d-86c8-dde8da783573.png)

Also jdom does not appear to be in the form of a OSGi bundle.  So I wonder where it will come from?

**Comment by merks** [comment] 2023-01-25 17:24
Maybe that's unrelated because the platform does use the older jdom...

**Comment by mickaelistria** [comment] 2023-01-25 17:24
jdom comes from (old) Orbit:  https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L69

**Comment by vogella** [comment] 2023-01-25 18:16
IIRC jxpath is used for the xpath support for E4 model fragments

**Comment by HannesWell** [comment] 2023-01-25 22:37
> I'm pretty sure that the root cause is the same as the one preventing #434 to be merged.

Agree with that.


> @akurtakov : I have no idea about things mentioned in #434. The question for me: is this something that **must** be fixed because it is a production issue or is this just unfortunate test setup / data that can be fixed?

It is probably kind of both. I think the root cause is #306/#343. `TestPDETemplates` uses the `ProductValidationOperation` but, like the validation in the Product-Editor, considers only the Plugins that are directly included into the product and doesn't add requirements automatically, even if the product is configured to do so. Therefore a regular launch just works, but the Valdidation in the Product-Editor failed with missing capabilities, just like that test.
I expect/hope that #438 fixes both.

**Closed** 2023-01-26 10:00 UTC
