### ISSUE TITLE
Validation button on product shows more issues than validation on runtime

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#306] opened 2022-08-23 07:46 UTC
Validation issues reported with the validation button on the product:

![image](https://user-images.githubusercontent.com/139910/186101307-7402eb78-380d-40c9-a284-c94fd727f539.png)

Validation issues reported with the validation button on the launch configuration:

![image](https://user-images.githubusercontent.com/139910/186101464-63003a59-26fd-4914-bb65-d282503f2175.png)

@HannesWell do we have two different validations? The one from the launch configuration displays correct results.

**Comment by vogella** [comment] 2022-08-23 14:51
> Have you tried a recent I-build?

This was with yesterdays I-build. 

>If not I can have a look at it next week when back from vacation.

Thanks

**Comment by HannesWell** [comment] 2023-01-25 22:24
> > If not I can have a look at it next week when back from vacation.
> 
> Thanks

I have to admit that haven't been on vacation for that long and simply forgot this. 😅
But it turned that this, just like #343 are the root cause for #437 and should all be fixed with #438.

**Closed** 2023-01-26 10:00 UTC
