### ISSUE TITLE
Failure of tests in org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest for I-BUILD I20240414-1800

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-pde/eclipse.pde#1234] opened 2024-04-15 15:24 UTC
See for example: https://download.eclipse.org/eclipse/downloads/drops4/I20240414-1800/testresults/html/org.eclipse.pde.ui.tests_ep432I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

These tests already failed before (#1205) but the stack-traces are not the same.

### `org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest.testImportSystemPackageDoesntAddExtraBundleJava8`

```java
java.lang.AssertionError:
Expecting no elements of:
["org.osgi.annotation.versioning_1.1.2.202109301733.jar",
"org.osgi.annotation.bundle_2.0.0.202202082230.jar",
"org.osgi.service.component.annotations_1.5.1.202212101352.jar",
"org.osgi.service.metatype.annotations_1.4.1.202109301733.jar",
"jakarta.annotation-api_2.1.1.jar"]
to match given predicate but this element did:
"jakarta.annotation-api_2.1.1.jar"
at java.base/java.util.Optional.ifPresent(Optional.java:178)
at org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest.testImportSystemPackageDoesntAddExtraBundleJava8(ClasspathResolutionTest.java:132) 
...
```

### `org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest.testImportSystemPackageDoesntAddExtraBundleJava8_osgiEERequirement`

```java
java.lang.AssertionError:
Expecting no elements of:
["org.osgi.annotation.versioning_1.1.2.202109301733.jar",
"org.osgi.annotation.bundle_2.0.0.202202082230.jar",
"org.osgi.service.component.annotations_1.5.1.202212101352.jar",
"org.osgi.service.metatype.annotations_1.4.1.202109301733.jar",
"jakarta.annotation-api_2.1.1.jar"]
to match given predicate but this element did:
"jakarta.annotation-api_2.1.1.jar"
at java.base/java.util.Optional.ifPresent(Optional.java:178)
at org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest.testImportSystemPackageDoesntAddExtraBundleJava8_osgiEERequirement(ClasspathResolutionTest.java:146) 
```

**Comment by iloveeclipse** [comment] 2024-04-15 15:25
Duplicate of https://github.com/eclipse-pde/eclipse.pde/issues/1227

**Closed by iloveeclipse** 2024-04-15 15:25 UTC
