### ISSUE TITLE
[target] consider other locations in planner mode

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#207] opened 2022-07-13 08:06 UTC
Currently in planner mode (if one selects include required software) PDE only takes into account other IU locations. It would be useful to either automatically or just always include content from other locations as well see for example tycho currently works this way and it becomes quite handy e.g. in combination with providing a missing bundle by a maven or directory target.

**Comment by jonahgraham** [comment] 2023-07-22 14:43
A real world example of where this is helpful is explained in #675.

**Comment by HannesWell** [comment] 2023-07-23 11:31
Support for this would be good.

In https://github.com/eclipse-pde/eclipse.pde/issues/675#issuecomment-1646525555 @merks suggested
> I suppose PDE might be made smarter such that it resolves all non-IUBundleContainer containers first, and is able to synthesis a p2 repository with all the resolved IUs and make those available when resolving the remaining IUBundleContainers. That sounds quite non-trivial...

In https://github.com/eclipse-pde/eclipse.pde/issues/675#issuecomment-1646538691 @laeubi responded
> > I suppose PDE might be made smarter such that it resolves all non-IUBundleContainer containers first, and is able to synthesis a p2 repository with all the resolved IUs and make those available when resolving the remaining IUBundleContainers. That sounds quite non-trivial...
> 
> Actually it is not _that_ complex but would require a two phase resolve operation, first collect and resolve all direct items and then perform the planner operation afterwards, that's how Tycho do it. But all this is _behavioral_ change, probably _breaking_ change and that's where it becomes not so trivial for anyone not liking getting punished for that.

@laeubi can you elaborate in more detail how a two phase resolution does solve this issue? At any point the content of other locations must be considered, but I don't understand how a two phase resolution would solve this auto-magically?
And in which cases would that be a breaking change? I always assumed that the result of the slicer is a sub-set of the planner?
Or do you mean a resolution in the PDEState? In general this has to be distinguished.

At the same time Ed's suggestion seems to be, at least from a theoretical point-of-view, relatively simple. I cannot access how difficult this would be to implement with P2.

**Comment by merks** [comment] 2023-07-23 11:50
One of the key components that does this/similar work for Oomph's targlets is org.eclipse.oomph.targlets.internal.core.TargletContainer.ComposedTargetContent.  (Did you know that Navigate -> Open Discovered Type.. can be used to find any Java top-level class in any Eclipse Git repository?)

It resolves each referenced/composed other *.target file and build/publishes IUs from the resulting bundles and features.  Those IUs are subsequently (after this first phase) used to augment those IUs otherwise available to the targlets via p2 URLs (during the second phase).  The same kind of thing could be done with ITargetLocation's bundles and features, first resolving the non IUBundleContainers and later using that IU metadata for the IUBundleContainers; I suppose only for the planner ones.

It's definitely feasible, and I'm no really sure how it's breaking any behavior.  At worst it mostly appears that it will help planners resolve things that otherwise don't resolve.  Though I suppose there is some reordering involved, but I don't see how order has any effect on the final content...

**Comment by laeubi** [comment] 2023-07-23 12:08
> I'm no really sure how it's breaking any behavior. At worst it mostly appears that it will help planners resolve things that otherwise don't resolve. Though I suppose there is some reordering involved, but I don't see how order has any effect on the final content...

Just a assume a Directory/Maven/... location that contains a newer version of a dependency then this might be chosen instead of the one from the P2 sites (even though it is there!) and then you not have both but only one version (the one from the Directory/Maven/...) in the target in contrast of two before.

I don't say its bad, its just *different* and what I learned it that people don't like that things are *different* than before...

**Comment by merks** [comment] 2023-07-23 12:54
That is a valid point.  Though one can have more specific ranges if one needs/wants two versions of some specific thing, and one can specify exact unit versions if one really want exactly a specific version.  

In the past, there were effectively only IUBundleContainers; that case I assume would not be affected because no action needs to be taken.  This case of other types of locations, particularly maven locations, is relatively new.  The past planner behavior leads (most) everyone to assume that the planners will see the IUs from the other locations, including the maven locations.

So yes, it's definitely possible that someone might be annoyed, and might complain about _any_ behavior change.  But then there are already people annoyed and complaining about it not behaving this way.   So now we are between a rock and a hard place.  😱

**Comment by HannesWell** [comment] 2023-07-23 13:38
> Just a assume a Directory/Maven/... location that contains a newer version of a dependency then this might be chosen instead of the one from the P2 sites (even though it is there!) and then you not have both but only one version (the one from the Directory/Maven/...) in the target in contrast of two before.

That's right, but I would say that's a change for the better and therefore ok. In the end the PDEState will wire all bundles to the latest version in that case anyway. So eventually that would even safe some bandwidth since the irrelevant version will not be downloaded.
And as Ed said, one can still add older versions explicitly as separate IU if desired.

> So yes, it's definitely possible that someone might be annoyed, and might complain about _any_ behavior change. But then there are already people annoyed and complaining about it not behaving this way. So now we are between a rock and a hard place. 😱

For those that would not want the new behavior yet another attribute, like `includeOtherLocations` could be added to the IU-location, that is set to true by default. So it is possible to opt-out.

**Comment by merks** [comment] 2023-07-23 14:08
> For those that would not want the new behavior yet another attribute, like `includeOtherLocations` could be added to the IU-location, that is set to true by default. So it is possible to opt-out.

We could add such a thing, but these things actually already **do** include other locations.  😱  

How about?

includeOtherNonIUContainerLocationsBecauseIWillComplainIfYouDoNotIgnoreOtherLocationsExceptOfCourseForOtherIUContainerLocationsWhichYouNeverIgnoredBefore  😕

**Comment by laeubi** [comment] 2023-07-23 14:16
> This case of other types of locations, particularly maven locations, is relatively new.

This is not new, the Directory and Install locations are there since "ever" and suffer from the same problem.

> For those that would not want the new behavior yet another attribute, like includeOtherLocations could be added to the IU-location, that is set to true by default. So it is possible to opt-out.

I won't add more confusing options, its already confusing enough for the user with too many options and help text referring to outdated stuff.

So either there is an agreement that "Include required software" (as it is named in the UI) means, include it from whatever is available (including other contributed ones) or we should better leave it alone instead of adding a new "Really include required software" checkbox.

**Comment by HannesWell** [comment] 2023-07-24 06:32
> includeOtherNonIUContainerLocationsBecauseIWillComplainIfYouDoNotIgnoreOtherLocationsExceptOfCourseForOtherIUContainerLocationsWhichYouNeverIgnoredBefore

Perfectly descriptive😜
Joke aside. I'm also fine not adding a new Attribute. It was intended as an optional Attribute to allow opting-out. But as it was said, there are other ways to get older versions if one really needs them.

Can anybody think of another drawback of the new approache?

**Comment by laeubi** [comment] 2023-07-24 06:38
> Can anybody think of another drawback of the new approache?

The main drawback in general is that this is wired to the `IULocation`, while actually from a user point of view the feature "Include required software" is more something I would want to select on the target level (like for run configs) **or** select for an individual location, while currently for this one needs to choose the same setting fro all `IULocation`s.

So given that it seems the Planner Mode is implemented in a way to gather everything, so given we now consider *more* locations, it might be that requirements from those are now considered as well, leading to a larger set of bundles or even new failures (because all other locations currently effectively using "slicer" mode and don't care about missing ones).

**Comment by merks** [comment] 2023-07-24 07:01
While it's not strictly true that all other locations currently effectively implement only slicer mode, because Oomph's targlet container supports both slicer and planner modes in isolation of all other locations

https://wiki.eclipse.org/Oomph_Targlets#Add_a_Targlet_Container

that doesn't negate the valid point that IUs from "other" locations when used by a IUBundleContainer in planner mode may be pulled into that IUBundleContainer's closure of requirements and that may lead to failure to transitively resolve all those requirements.  Though, as I write this, I wonder if that's actually true.  After all, if that IUBundleContainer can resolve without such additional available IUs, then introducing additional IUs should not make the SAT problem unsolvable, should it?  I suspect the only drawback is that it might solve the problem differently (smaller, larger, not the same) than before.  Of course that drawback is also the goal!

**Comment by jcompagner** [comment] 2023-10-09 09:54
[test_target.zip](https://github.com/eclipse-pde/eclipse.pde/files/12844605/test_target.zip)

here i have a test.target that i think should resolve
the "dltk" project does have a depedency on antlr4 that it doesn't ship (not in this test version)
and i added a mvn depedency to that but eclipse target editor still complains

the only way to fix this quickly for me is that dltk feature also includes antlr4 (which comes from a target with a mvn depedency)
So that the dltk repo site provides it them selfs.

dltk also depends on emf (which it doesn't ship) and that i have to add in my target as a p2 site that works. but if that would also be a mvn jar then it would also fail

**Closed** 2023-10-23 06:18 UTC

**Comment by HannesWell** [comment] 2023-10-24 21:27
Thank you @laeubi for solving this long standing issue. Great work!
