### ISSUE TITLE
Eclipse 4.31 RC1 Drawing error with macOS when running "PDE" or "Product" project

### ISSUE THREAD

**Issue by minduch** [eclipse-pde/eclipse.pde#1182] opened 2024-03-03 18:13 UTC
Running or debugging a PDE or Product from Eclipse does not display the windows properly, only some parts inside the windows are drawn.

Mac OS Sonoma, Mac Mini Pro 2, AArch64 - with Eclipse 4.31 RC1. This problem did not exist in Eclipse 4.30 on same machine/OS/Java version. It doesn't matter the Java (Temurin) version: 17 or 21, it produces the same error. It works fine under Windows (11) with a similar configuration, Eclipse+Java versions. We first saw this problem in Eclipse 4.31 M2 (as we didn't try it out on M1).

Eclipse itself drawn nicely, and also the Product when compiled and run outside of Eclipse, but from inside Debug or Run, there is no way of really seeing anything, so debugging becomes impossible.

Screen capture:
<img width="632" alt="image" src="https://github.com/eclipse-pde/eclipse.pde/assets/28196566/a6d748c9-2448-4e23-9749-f76d8455fdbe">

**Comment by iloveeclipse** [comment] 2024-03-03 18:17
Duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012

**Closed by iloveeclipse** 2024-03-03 18:17 UTC
