### ISSUE TITLE
Add support for excluding a plug-in from a p2 update site in the target platform

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#922] opened 2023-11-14 11:24 UTC
Similar to the option to exclude certain libraries in the Maven dependencies it would be nice if we had an exclude for p2 update sites also.

Exclude in Maven:

````
<dependency>
	<groupId>org.group</groupId>
	<artifactId>artifact1</artifactId>
	<exclusions>
		<exclusion>
			<groupId>bad.group</groupId>
			<artifactId>artifact3</artifactId>
		</exclusion>
	</exclusions>
</dependency>
````
Exclude in M2E target (in the future M2E might support the standard Maven way, see https://github.com/eclipse-m2e/m2e-core/issues/286)

````
<location includeDependencyDepth="infinite" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
		    <dependencies>
			    <dependency>
				    <groupId>org.apache.commons</groupId>
				    <artifactId>commons-geometry-euclidean</artifactId>
				    <version>1.0</version>
				    <type>jar</type>
			    </dependency>
		    </dependencies>
		    <exclude>org.apache.commons:commons-numbers-quaternion:1.0</exclude>
	    </location>
    </locations>
````

For p2 update sites we only have (as far as I know) includeBundles which apply for the whole set of plug-ins

```
	<includeBundles>
		<plugin id="com.jcraft.jsch"/>
	</includeBundles>
```

**Comment by laeubi** [comment] 2023-11-14 11:31
@vogella please see:

https://github.com/eclipse-pde/eclipse.pde/issues?q=is%3Aissue+is%3Aopen+exclude

what reveals
- https://github.com/eclipse-pde/eclipse.pde/issues/293

**Comment by laeubi** [comment] 2023-11-14 11:32
Duplicate of #293

**Closed by laeubi** 2023-11-14 11:32 UTC

**Comment by vogella** [comment] 2023-11-14 11:41
@laeubi slightly different request but fine to tried this as dup for me

**Comment by laeubi** [comment] 2023-11-14 11:45
The you probabbly want to reopen/rephrase this, `<includeBundles>` you mentioned is global for the target and not usable in IU locations.

Also for P2 one better would use filters like Tycho offers as it usually is not enough to reference it by id/name:
- https://tycho.eclipseprojects.io/doc/latest/target-platform-configuration/target-platform-configuration-mojo.html#filters

**Comment by vogella** [comment] 2023-11-14 11:47
> The you probabbly want to reopen/rephrase this, `<includeBundles>` you mentioned is global for the target and not usable in IU locations.

Yes, that is why I wrote " we only have (as far as I know) includeBundles which apply for the whole set of plug-ins" describing the current state.

**Comment by laeubi** [comment] 2023-11-14 11:53
Actually it was "For p2 update sites we only have" but don't want to be picky here, one thing that needs to be considered is that if using planner mode, IUs of different locations are considered as belong to "this", so one obviously want to take this into account as IU locations are very special in the first place, also it needs to be decided if resolution must fail if I exclude something that is required (but why I include it then?) and should such things be show and so on so it is not a trivial task.

**Comment by vogella** [comment] 2023-11-14 11:57
> Actually it was "For p2 update sites we only have" but don't want to be picky here, one thing that needs to be considered is that if using planner mode, IUs of different locations are considered as belong to "this", so one obviously want to take this into account as IU locations are very special in the first place, also it needs to be decided if resolution must fail if I exclude something that is required (but why I include it then?) and should such things be show and so on so it is not a trivial task.

Consistent behavior with the current M2E behavior is desired (infinite dependencies with excludes, not failing if a lib is excluded).

**Comment by merks** [comment] 2023-11-14 12:10
Note that the planner mode example is somewhat confusing.  Firstly the planner does not know Maven coordinates.  Secondly the planner will include something only if it's required by the things explicitly listed, so one can't really exclude something from the planner, without making the plan fail, except maybe in the rare case of there only being optional greedy requirements on the to-be-excluded thing.  So for IULocations, I think at best one can, separately from the resolution process, exclude availability of the full set of things.  But that still leaves the issue of not all requirements being resolved, making it not possible to launch.   

That's a long winded way of saying this looks somewhat unimplementable to me.

**Comment by vogella** [comment] 2023-11-14 12:17
@merks these days you could use pure m2e dependencies for plug-in development and all issues I can extract from your statement are similar if you use m2e requirements with excludes. 

Excludes for p2 update sites could of course lead to a failing launch and excludes in M2E requirements could also lead to this. The use case for excludes is typically to exclude a certain artifact because you plan to use another version or another source for this.

**Comment by laeubi** [comment] 2023-11-14 12:20
@merks yes I think you have expressed it better than me ;-)

because the rare times I wanted that feature was because there are some conflicts between IU Location 1 + IULocation 2 and planner fails... today I would just use two targets and include these in my main target file or make sure all dependencies are up to date so they do not conflict.

m2e locations on the other hand work **completely different** as they never "plan" anything on the OSGi level, just provided what was declared in the pom and they don't care about other locations.
