### ISSUE TITLE
Error validating SDK launch due missing JRE 1.1 support

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1231] opened 2024-04-15 11:40 UTC
After removing support for JRE 1.1 (https://github.com/eclipse-equinox/equinox/pull/572 & https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/424) there is a validation error shown on startup of SDK from SDK.

PDE should update it's logic to validate launches.

![image](https://github.com/eclipse-pde/eclipse.pde/assets/964108/12c40bf7-0935-4d99-b232-2c013f0a3923)

**Comment by akurtakov** [comment] 2024-04-15 12:28
@merks As this one comes from Orbit I would say that the fix should be there, no?

**Comment by iloveeclipse** [comment] 2024-04-15 12:29
PDE allows to use **any** libraries in the platform, and PDE can be used to debug older platforms.
So the fix must be in PDE / SDK.

**Comment by merks** [comment] 2024-04-15 12:43
There's nothing wrong with such a requirement.  Even the latest Java 21 provides those system capabilities:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/35e929d7-cba0-4101-8669-8e7aa71357ff)

So if PDE says those capabilities are missing, it's not looking at the right thing or not looking in the right way.

**Comment by akurtakov** [comment] 2024-04-15 12:50
Acked about capability being provided and thus PDE fix is due.
https://github.com/eclipse-equinox/equinox/issues/571#issuecomment-2046055636 makes me believe that we should try to not ship bundles with "non-standard" EEs.

**Comment by merks** [comment] 2024-04-15 13:20
FYI, for history, you can see this issue:

https://github.com/eclipse-orbit/orbit/issues/52

This legacy bundle is a drop-in replacement for this:

https://repo1.maven.org/maven2/xml-apis/xml-apis-ext/1.3.04/

That thing provides no source.  If it did, I would have just wrapped in with m2e/tycho BND support which would produce this manifest:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/7b59aae7-903b-4dc7-86a5-6d88ea7839e6)

So standard or not, BND produces that and org.eclipse.osgi.storage.Storage.calculateEECapabilities(Version) computes that, so I tried to reproduce something that includes actual sources and that follows that same expect result.

**Comment by HannesWell** [comment] 2024-04-15 18:33
> PDE allows to use **any** libraries in the platform, and PDE can be used to debug older platforms. So the fix must be in PDE / SDK.

Yes. After all I think it is simpler to just revert the removal in Equinox instead of cleaning up everthing from JRE-1.1. There are some left-overs of it in Equinox (e.g. what Ed mentioned) and also in PDE etc.
Created https://github.com/eclipse-equinox/equinox/pull/596 to revert it and add the system-packages currently hard-coded in PDE.
To fully fix this issue https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/425 has to be reverted because PDE relies on the EE JDT provides. So at least the `JRE-1.1` EE must be restored in JDT.

Once https://github.com/eclipse-equinox/equinox/pull/596  is submitted the following hard-coded list can be removed from PDE:
https://github.com/eclipse-pde/eclipse.pde/blob/860100e5b0d57bca42cbe26078ea5c3093828c60/build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java#L580-L603

**Comment by iloveeclipse** [comment] 2024-04-16 09:08
> Once [eclipse-equinox/equinox#596](https://github.com/eclipse-equinox/equinox/pull/596) is submitted the following hard-coded list can be removed from PDE

@HannesWell : do you plan to provide a PR for that?

**Comment by HannesWell** [comment] 2024-04-16 22:26
> > Once [eclipse-equinox/equinox#596](https://github.com/eclipse-equinox/equinox/pull/596) is submitted the following hard-coded list can be removed from PDE
> 
> @HannesWell : do you plan to provide a PR for that?

See https://github.com/eclipse-pde/eclipse.pde/pull/1239.

With https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/431 being merged I think this is resolved.
Thank you @iloveeclipse for providing the PR for JDT.

**Closed by HannesWell** 2024-04-16 22:26 UTC
Labels: bug, regression
