### ISSUE TITLE
org.eclipse.pde.api.tools.tests has 611 failing tests with Tycho Surefire, nightly build is fine

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#232] opened 2022-07-25 10:32 UTC
See https://ci.eclipse.org/pde/job/eclipse.pde.ui/job/master/101/
and https://download.eclipse.org/eclipse/downloads/drops4/I20220724-1800/testresults/html/org.eclipse.pde.api.tools.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

Looks like all org.eclipse.pde.api.tools.builder.tests.compatibility tests are failing on Jenkins after this PR https://github.com/eclipse-pde/eclipse.pde/pull/227.

Typical fail looks like:

```
junit.framework.AssertionFailedError: The project was not found in the workspace baseline: bundle.a
	at org.eclipse.pde.api.tools.builder.tests.compatibility.BundleVersionTests.setupTest(BundleVersionTests.java:161)
	at org.eclipse.pde.api.tools.builder.tests.compatibility.BundleVersionTests.test003(BundleVersionTests.java:223)
```

Reverting https://github.com/eclipse-pde/eclipse.pde/pull/227 fixes tests on Jenkins.
???

**Comment by laeubi** [comment] 2022-07-25 17:27
@mickaelistria @akurtakov any idea why API tools failing now?

**Comment by akurtakov** [comment] 2022-07-25 17:30
No idea. I pushed https://github.com/eclipse-pde/eclipse.pde/commit/b4ec281656556256554c6b4ab68870d014e8003e today so we are on the safe side but I haven't looked into more details.

**Comment by merks** [comment] 2022-07-25 17:37
Could this be related?

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/419

**Comment by laeubi** [comment] 2022-07-25 17:41
@merks it is not that the API **check** is failing but the API tool **test** itself.

**Comment by laeubi** [comment] 2022-07-25 17:50
I triggered a new build now jsut in case it was something temporal... https://ci.eclipse.org/pde/job/eclipse.pde.ui/job/master/

**Comment by laeubi** [comment] 2022-07-25 18:33
The log currently shows a lot of
```

[INFO] --- tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) @ org.eclipse.pde.genericeditor.extension.tests ---
20:14:12  [INFO] Compiling 12 source files to /home/jenkins/agent/workspace/eclipse.pde.ui_master/ui/org.eclipse.pde.genericeditor.extension.tests/target/classes
20:14:12  Failed to init Classpath for jar file /home/jenkins/agent/workspace/eclipse.pde.ui_master/.m2/repository/org/ow2/sat4j/org.ow2.sat4j.pb/2.3.6/org.sat4j.core.jar
20:14:12  java.nio.file.NoSuchFileException: /home/jenkins/agent/workspace/eclipse.pde.ui_master/.m2/repository/org/ow2/sat4j/org.ow2.sat4j.pb/2.3.6/org.sat4j.core.jar
20:14:12  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
20:14:12  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
20:14:12  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
20:14:12  	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
20:14:12  	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
20:14:12  	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
20:14:12  	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
20:14:12  	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
20:14:12  	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
20:14:12  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
20:14:12  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
20:14:12  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
20:14:12  	at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:201)
20:14:12  	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
20:14:12  	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
20:14:12  	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
20:14:12  	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
20:14:12  	at org.eclipse.tycho.compiler.jdt.JDTCompiler.compileInProcess(JDTCompiler.java:370)
20:14:12  	at org.eclipse.tycho.compiler.jdt.JDTCompiler.performCompile(JDTCompiler.java:123)
20:14:12  	at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:414)
```

**Comment by iloveeclipse** [comment] 2022-07-25 18:49
> The log currently shows a lot of

Just a hint, not necessarily the root cause.
They are printed since https://github.com/eclipse-jdt/eclipse.jdt.core/pull/239

**Comment by iloveeclipse** [comment] 2022-07-25 19:25
So now I would like to understand what's going on here, and why this innocent patch broke PDE tests on **Jenkins only** :  #235 ?!?

**Comment by iloveeclipse** [comment] 2022-07-25 19:49
I have an idea: the "var" could be differently resolved depending on dependencies on classpath? They may differ between official build and Jenkins one.

Let's see if #236 would be broken too.

**Comment by iloveeclipse** [comment] 2022-07-25 20:14
> Let's see if #236 would be broken too.

Same issue. So not the compiler to blame. 
Next: the NPE that is supposed to be prevented is **required** for PDE tests to succeed ?!?

**Comment by iloveeclipse** [comment] 2022-07-25 20:46
> Next: the NPE that is supposed to be prevented is **required** for PDE tests to succeed ?!?

YES !!!

See https://ci.eclipse.org/pde/job/eclipse.pde.ui/job/PR-236/2/

OMG. What kind of ~~code~~ hack is it?

Note: I can't see system error printing I've added before throwing NPE, Jenkins seem to redirect it somewhere where it doesn't disturb anyone who runs tests. Makes sense, for sure.

**Comment by laeubi** [comment] 2022-07-26 03:54
> > The log currently shows a lot of
> 
> Just a hint, not necessarily the root cause. They are printed since [eclipse-jdt/eclipse.jdt.core#239](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/239)

Yes that was just an observation so "something" is wrong here when Tycho is passing the classpath to the compiler and should obviously not happen, I will check if I can get some better output from Tycho itself...

> OMG. What kind of ~code~ hack is it?

![The only valid measurement of code quality is WTFs/minute](https://i.redd.it/btd5aebzr5h01.jpg)
https://www.reddit.com/r/ProgrammerHumor/comments/7ym547/the_only_valid_measurement_of_code_quality_is/

> Note: I can't see system error printing I've added before throwing NPE, Jenkins seem to redirect it somewhere where it doesn't disturb anyone who runs tests. Makes sense, for sure.

I think you can make the test `fail()` at the end and then Jenkins shows you the STD-OUT in the test report.

**Comment by mickaelistria** [comment] 2022-07-28 07:57
Note that you can reproduce the issue locally with
```
$ cd eclipse.pde.ui/apitools/org.eclipse.pde.api.tools.tests
$ mvn clean verify -Pbuild-individual-bundles -Dtycho.localArtifacts=ignore
```
and can even add the `-DdebugPort=8000` option to the Maven command to allow hooking a debugger to the test execution.

**Comment by mickaelistria** [comment] 2022-07-28 22:45
Seems like everything is back to normal (eg #236 succeeds). I guess it was some issue upstream, for example in how encoding can now generate an error, or in some transitive dependency...

**Comment by laeubi** [comment] 2022-07-29 16:06
Still randomly occurs....

**Comment by mickaelistria** [comment] 2022-07-29 16:09
> Still randomly occurs....

Can you please point to an example where this still happens?

**Comment by laeubi** [comment] 2022-07-29 16:10
See for example https://ci.eclipse.org/pde/job/eclipse.pde.ui/job/PR-248/1/ master build now fails with another test that indicates an API bundle was disposed, ...

**Comment by mickaelistria** [comment] 2022-07-29 16:18
Actually, it was never fixed. I looked at the wrong repo earlier...

**Comment by iloveeclipse** [comment] 2022-08-12 06:13
Still see the problem in https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-286/1/ on https://github.com/eclipse-pde/eclipse.pde/pull/286.

#286 can't cause that! But it always fails with this PR.

**Comment by laeubi** [comment] 2022-08-12 06:24
Its random ... sometimes I get a green CI, then on the next change (e.g. adjust the javadoc or rebase, ...) it fails. I tried to debug the tests, but as it is not reliable reproachable its hard to guess whats wrong and I even don't understand enough how these API tools stuff works.

**Comment by iloveeclipse** [comment] 2022-08-12 21:37
**Seven build fails in a row**:
https://ci.eclipse.org/pde/job/eclipse.pde/view/change-requests/job/PR-286/

This cannot be by accident.
I've tried to add trivial changes from other projects to the PR just to see if that has any influence.
But by all means,  I can't find any relationship between the trivial change in the PR and the test failures.

**Comment by HannesWell** [comment] 2022-08-13 17:34
https://github.com/eclipse-pde/eclipse.pde/pull/289 only fails on GH but not on Jenkins.

**Comment by HannesWell** [comment] 2022-08-16 21:14
I can reproduce the failures when I build PDE locally. I started debugging it a but, but my knowledge about the internals of API-tools is very low, so I did not yet find a reason for sure, just one guess for that I created https://github.com/eclipse-pde/eclipse.pde/pull/296.

**Comment by jukzi** [comment] 2022-09-23 09:55
no fun to contribute to PDE with 611 failing test

**Comment by HannesWell** [comment] 2022-09-24 12:52
> no fun to contribute to PDE with 611 failing test

That's no fun for anybody involved. But just mentioning it does not help to solve the issue.

As you can see multiple persons already tried to solve the issue. As said in https://github.com/eclipse-pde/eclipse.pde/pull/296 I suspect that some projects from previous runs leak into the workspace for a following test case. Maybe due to a change in Tycho or somewhere else in the platform? I debugged the build locally in the past and tried a few things but had no luck so far as well.
I can search further in the future, but any help/participation would be highly appreciated.

**Comment by mickaelistria** [comment] 2022-10-01 10:38
I'm thinking maybe the issue comes from the detected JRE. I can easily and constantly reproduce the issue locally where only Java 18 and Java 11 are installed.
Running the test locally and looking at report shows that `ProjectTypeContainerTests.setUp()` is the 1st failure in the suite. I debug the failure as described in https://github.com/eclipse-pde/eclipse.pde/issues/232#issuecomment-1197797747 and put a breakpoint on the line that logs `The project was not found in the workspace baseline: ` when the value is null. Then I inspect the `bundle.a` project and see that *it cannot be built* because of 1 error `Marker [on: /bundle.a/src/a/classes/hierarchy/RemoveConstructorFromInternalSuperclass.java, id: 343, type: org.eclipse.jdt.core.problem, attributes: [arguments: 2:a.classes.internal.InternalClassWithConstructor#   , categoryId: 50, charEnd: 760, charStart: 721, id: 134217868, lineNumber: 21, message: Implicit super constructor InternalClassWithConstructor() is undefined for default constructor. Must define an explicit constructor, severity: 2, sourceId: JDT], created: 10/1/22, 11:54 AM]` and a bunch of other errors related to J2SE-1.5 not being perfectly matched. I imagine that if this project cannot be built, it can hardly be used in the baseline.
IIRC, older Java versions are installed and used by JDT on the I-Build tests, so that could cause the difference; and maybe also cause the difference on CI from 1 node to the other...

**Comment by laeubi** [comment] 2022-10-01 11:34
> related to J2SE-1.5

Do we really should consider Java 1.5 (!) here?

Looking at org.eclipse.pde.api.tools.internal.APIFileGenerator.resolveCompliance(Map<String, String>) it seems API tools is not updated a long time as it only seem to support Java up to 1.8 ...

**Comment by laeubi** [comment] 2022-10-01 11:42
I created:
- https://github.com/eclipse-pde/eclipse.pde/pull/352

to see if more java versions are helping here (using Java 8, Java 11, Java 17)

**Comment by mickaelistria** [comment] 2022-10-01 13:07
When on that breakpoint, I see on manager.workspaceBaseline.fEEStatus="Status ERROR: org.eclipse.pde.api.tools code=0 Baseline not bound - there are no installed VMs compatible with the required execution environments".

@laeubi let's first ensure about the cause and possible remediation before challenging the current state of art. It could be that keeping some support for J2SE-1.5 is actually simpler than dropping it.

**Comment by laeubi** [comment] 2022-10-02 05:50
> It could be that keeping some support for J2SE-1.5 is actually simpler than dropping it.

Obviousness it does not work to that well, anyways I adjusted the GH build to include java 1.8 and it seems to have only one failing test left:
https://github.com/eclipse-pde/eclipse.pde/pull/315

**Comment by mickaelistria** [comment] 2022-10-02 07:59
I've kept investigating the issue and reduced the case to 7 test suites that running together show the issue; but remove any of those and the issue disappears and tests suddenly work... It seems like there are a bunch of side-effects at play that make that those tests are badly affected by lots of unrelated things.

**Comment by HannesWell** [comment] 2022-10-05 07:16
> I've kept investigating the issue and reduced the case to 7 test suites that running together show the issue; but remove any of those and the issue disappears and tests suddenly work... It seems like there are a bunch of side-effects at play that make that those tests are badly affected by lots of unrelated things.

Can you post a List of those 7 tests or provide a draft PR with the stripped down test-suite?

**Comment by mickaelistria** [comment] 2022-10-05 16:42
See https://github.com/eclipse-pde/eclipse.pde/pull/354 which constantly results in 1 test failure on my machine, and any time I tweak the suite, the failing test starts passing...

**Comment by HannesWell** [comment] 2023-02-13 18:33
Fixed via https://github.com/eclipse-pde/eclipse.pde/pull/456

**Closed by HannesWell** 2023-02-13 18:33 UTC
Labels: api-tools
