### ISSUE TITLE
Automatically add org.eclipse.pde.api.tools.annotations to buildpath if api nature is enabled

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#909] opened 2023-11-12 06:32 UTC
I just noticed that there is a project `org.eclipse.pde.api.tools.annotations` that supply code annotations for API tools, a quick search reveled that they are nearly unused (only found a few reference in whole code), most probably because its hard to discover and clumsy to configure.

Similar to the DS annotations, we should simply make them available when the api tools nature is present at the project.

**Comment by HannesWell** [comment] 2023-11-12 09:54
Duplicate of #447

**Comment by HannesWell** [comment] 2023-11-12 09:54
> Duplicate of #447

I think we can therefore close this and handle this as #447

**Closed by HannesWell** 2023-11-12 09:54 UTC
