### ISSUE TITLE
osgi.ee contraints are not shwon in the Manifest editor

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#466] opened 2023-02-11 09:04 UTC
This is for example how it currently looks in PDE for `org.eclipse.osgi` that already uses `osgi.ee`

![grafik](https://user-images.githubusercontent.com/1331477/218249749-42140cc2-df50-44c6-a500-67df8dd73485.png)

The red marked part is just empty and should actually show `JavaSE-1.8` as defined here:
`Require-Capability: osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"`

also the editor do not allow adding things to `osgi.ee` ...

**Comment by HannesWell** [comment] 2023-02-15 23:34
Duplicate of #140

**Closed** 2023-02-15 23:35 UTC
